name: flutter_project_structure
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  package_info_plus: ^4.0.2
  logger: ^1.4.0
  connectivity_plus: ^4.0.1
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  flutter_screenutil: ^5.8.4
  flutter_native_splash: ^2.3.1
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  freezed_annotation: ^2.2.0
  permission_handler: ^10.4.1
  dio: ^5.2.1+1
  retrofit: ">=4.0.0 <5.0.0"
  json_annotation: ^4.8.1

  #Firebase Packages
  firebase_core: ^2.14.0
  firebase_crashlytics: ^3.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.6
  freezed: ^2.3.5
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.7
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/
